name: Go

on:
  push:
    branches: [ "main", "basic_write","markdown","placeholder" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.1' # Ensure this version number is correct and available

    - name: Build
      run: go build -v ./...

    - name: Clean
      run: go clean -cache -testcache -modcache

    - name: Test
      run: go test -v ./...
